<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Higher-Order Network Analysis with Simplicial Complexes • Nestimate</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png">
<link rel="icon" type="”image/svg+xml”" href="../favicon.svg">
<link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png">
<link rel="icon" sizes="any" href="../favicon.ico">
<link rel="manifest" href="../site.webmanifest">
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.8/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.8/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="cograph-tutorial-simplicial_files/libs/quarto-html/popper.min.js"></script><script src="cograph-tutorial-simplicial_files/libs/quarto-html/tippy.umd.min.js"></script><link href="cograph-tutorial-simplicial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cograph-tutorial-simplicial_files/libs/quarto-html/light-border.css" rel="stylesheet">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Higher-Order Network Analysis with Simplicial Complexes">
<meta property="og:image" content="https://saqr.me/Nestimate/logo.svg">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">Nestimate</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.7.3</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-articles" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Articles</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-articles">
<li><a class="dropdown-item" href="../articles/transition-networks.html">Network Estimation and Analysis with Nestimate</a></li>
    <li><a class="dropdown-item" href="../articles/sequence-comparison.html">Sequence Pattern Comparison: Early vs Late Human-AI Interactions</a></li>
    <li><a class="dropdown-item" href="../articles/sequence-plots.html">Sequence Plots: heatmap, index, and distribution</a></li>
    <li><a class="dropdown-item" href="../articles/clustering.html">Sequence Clustering</a></li>
    <li><a class="dropdown-item" href="../articles/markov-stability.html">Markov Stability Analysis</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="../articles/index.html">More articles...</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/mohsaqr/Nestimate/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.svg" class="logo" alt=""><h1>Higher-Order Network Analysis with Simplicial Complexes</h1>
      <p class="subtitle">From Transition Networks to Topological Analysis</p>
      <p class="author">Mohammed SaqrSonsoles López-PernasKamila Misiejuk</p>
      <p class="date">2026-06-21</p>

      <small class="dont-index">Source: <a href="https://github.com/mohsaqr/Nestimate/blob/main/vignettes/articles/cograph-tutorial-simplicial.qmd" class="external-link"><code>vignettes/articles/cograph-tutorial-simplicial.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <section class="level2"><h2 id="introduction">Introduction<a class="anchor" aria-label="anchor" href="#introduction"></a>
</h2>
<p>When we analyze sequential data as a network — who follows whom, which state leads to which — we typically build a <strong>first-order Markov model</strong>: the probability of the next state depends only on the current state. This is the foundation of Transition Network Analysis (TNA).</p>
<p>But human behavior is not always memoryless. Consider two programmers working with an AI coding assistant:</p>
<ul>
<li>Programmer A: <em>Specify → Request → Specify → Request</em> (a steady back-and-forth)</li>
<li>Programmer B: <em>Frustrate → Specify → Request → Command</em> (escalating from frustration to direct commands)</li>
</ul>
<p>In a first-order model, both sequences contribute equally to the <em>Specify → Request</em> transition. But the <strong>context</strong> — what came before — matters. The sequence <em>Frustrate → Specify</em> may lead to very different next actions than <em>Request → Specify</em>. These are <strong>higher-order dependencies</strong>: cases where the past two (or more) states jointly predict the future better than the current state alone.</p>
<p>This tutorial introduces a complete pipeline for detecting, quantifying, and visualizing higher-order structure in sequential data. We progress from standard transition networks through statistical order detection, pathway analysis, and into the topology of higher-order interactions using simplicial complexes.</p>
<section class="level3"><h3 id="what-you-will-learn">What you will learn<a class="anchor" aria-label="anchor" href="#what-you-will-learn"></a>
</h3>
<ol type="1">
<li>Test whether your data has higher-order dependencies (and at what order)</li>
<li>Identify which specific pathways deviate from first-order expectations</li>
<li>Detect anomalously frequent or rare behavioral sequences</li>
<li>Compute topological invariants (Betti numbers, Euler characteristic)</li>
<li>Track how network topology changes across thresholds (persistent homology)</li>
<li>Visualize higher-order pathways as simplicial blob diagrams</li>
<li>Compare higher-order structure across groups</li>
</ol></section><section class="level3"><h3 id="packages">Packages<a class="anchor" aria-label="anchor" href="#packages"></a>
</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/mohsaqr/Nestimate" class="external-link">Nestimate</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://sonsoles.me/cograph/" class="external-link">cograph</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Guard cograph::plot_simplicial() against grDevices::chull() failing on</span></span>
<span><span class="co"># degenerate pathway clouds (collinear / single-point), which the CRAN</span></span>
<span><span class="co"># cograph (2.1.1) hits but the dev build (&gt;= 2.3.5) fixes in .smooth_blob().</span></span>
<span><span class="co"># Shadow the function in the knit env so all call sites fall back to</span></span>
<span><span class="co"># splot() with a warning rather than aborting the render. Package code is</span></span>
<span><span class="co"># unaffected (scope is this vignette's knit environment only).</span></span>
<span><span class="va">plot_simplicial</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">...</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">args</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span><span class="va">...</span><span class="op">)</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/conditions.html" class="external-link">tryCatch</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/do.call.html" class="external-link">do.call</a></span><span class="op">(</span><span class="fu">cograph</span><span class="fu">::</span><span class="va"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span>, <span class="va">args</span><span class="op">)</span>,</span>
<span>           error <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">e</span><span class="op">)</span> <span class="op">{</span></span>
<span>             <span class="kw"><a href="https://rdrr.io/r/base/warning.html" class="external-link">warning</a></span><span class="op">(</span><span class="st">"plot_simplicial fell back to splot(): "</span>,</span>
<span>                     <span class="fu"><a href="https://rdrr.io/r/base/conditions.html" class="external-link">conditionMessage</a></span><span class="op">(</span><span class="va">e</span><span class="op">)</span>, call. <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span>             <span class="fu"><a href="https://sonsoles.me/cograph/reference/splot.html" class="external-link">splot</a></span><span class="op">(</span><span class="va">args</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span>           <span class="op">}</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
</div>
<p><strong>cograph</strong> provides the simplicial visualization (<code><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial()</a></code>). <strong>Nestimate</strong> provides the higher-order network construction (<code>build_hon</code>, <code>build_hypa</code>, <code>build_mogen</code>) and simplicial complex analysis (<code>build_simplicial</code>, <code>betti_numbers</code>, <code>persistent_homology</code>, <code>q_analysis</code>).</p>
</section></section><section class="level2"><h2 id="building-the-network">Building the Network<a class="anchor" aria-label="anchor" href="#building-the-network"></a>
</h2>
<p>We use a dataset of human–AI pair programming sessions where a researcher coded each human action into 9 behavioral categories: Request, Specify, Command, Correct, Refine, Verify, Inquire, Interrupt, and Frustrate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="st">"human_long"</span>, package <span class="op">=</span> <span class="st">"Nestimate"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">net</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_network.html">build_network</a></span><span class="op">(</span><span class="va">human_long</span>, method <span class="op">=</span> <span class="st">"relative"</span>,</span>
<span>                     action <span class="op">=</span> <span class="st">"code"</span>, actor <span class="op">=</span> <span class="st">"session_id"</span>,</span>
<span>                     time <span class="op">=</span> <span class="st">"timestamp"</span><span class="op">)</span></span>
<span><span class="va">net</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Transition Network (relative probabilities) [directed]
  Weights: [0.018, 0.620]  |  mean: 0.111

  Weight matrix:
            Command Correct Frustrate Inquire Interrupt Refine Request Specify
  Command     0.235   0.088     0.055   0.066     0.035  0.038   0.155   0.280
  Correct     0.093   0.091     0.138   0.057     0.054  0.112   0.120   0.278
  Frustrate   0.103   0.115     0.176   0.075     0.047  0.171   0.111   0.125
  Inquire     0.196   0.126     0.098   0.188     0.094  0.062   0.084   0.106
  Interrupt   0.259   0.081     0.094   0.123     0.102  0.080   0.069   0.122
  Refine      0.058   0.075     0.072   0.047     0.042  0.086   0.146   0.457
  Request     0.096   0.019     0.044   0.067     0.051  0.033   0.039   0.620
  Specify     0.263   0.058     0.081   0.072     0.167  0.074   0.070   0.172
  Verify      0.224   0.079     0.164   0.118     0.043  0.097   0.116   0.083
            Verify
  Command    0.048
  Correct    0.056
  Frustrate  0.077
  Inquire    0.044
  Interrupt  0.069
  Refine     0.018
  Request    0.032
  Specify    0.043
  Verify     0.077

  Initial probabilities:
  Specify       0.679  ████████████████████████████████████████
  Command       0.175  ██████████
  Request       0.055  ███
  Interrupt     0.030  ██
  Correct       0.019  █
  Refine        0.019  █
  Frustrate     0.013  █
  Inquire       0.008
  Verify        0.002  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://sonsoles.me/cograph/reference/splot.html" class="external-link">splot</a></span><span class="op">(</span><span class="va">net</span>, minimum <span class="op">=</span> <span class="fl">0.05</span>, title <span class="op">=</span> <span class="st">"Human Actions in AI-Assisted Coding"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/plot-network-1.png" width="864"></p>
</figure>
</div>
</div>
</div>
<p>Several patterns stand out: <strong>Specify</strong> is the hub — most actions lead to and from it. Self-loops on Specify and Command indicate persistence. The <strong>Request → Specify → Command</strong> backbone reflects the natural workflow. But this first-order view might be hiding important patterns. Does it matter <em>how</em> someone arrived at Specify?</p>
</section><section class="level2"><h2 id="is-first-order-enough-multi-order-model-selection">Is First-Order Enough? Multi-Order Model Selection<a class="anchor" aria-label="anchor" href="#is-first-order-enough-multi-order-model-selection"></a>
</h2>
<p>Before investing in higher-order analysis, we should answer: <strong>does sequential memory actually matter?</strong> The Multi-Order Generative Model (MOGen; Scholtes 2017) fits Markov models at increasing orders and compares them using information criteria. Higher-order models fit better but have exponentially more parameters — AIC and BIC find the best tradeoff.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mg</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_mogen.html">build_mogen</a></span><span class="op">(</span><span class="va">net</span>, max_order <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">mg</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Multi-Order Generative Model (MOGen) Summary

  States: Command, Correct, Frustrate, Inquire, Interrupt, Refine, Request, Specify, Verify
  Paths: 508 | Observations: 10778
  Best by AIC: order 4  |  Best by BIC: order 1
  Selected:    order 4 (by aic)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        order layer_dof cum_dof    loglik      aic      bic best selected
order_0     0         8       8 -22001.20 44018.40 44076.68
order_1     1        72      80 -20805.61 41771.23 42354.05  BIC
order_2     2       621     701 -19819.55 41041.10 46148.07
order_3     3      2445    3146 -17152.10 40596.20 63515.63
order_4     4      2990    6136 -11469.73 35211.46 79913.83  AIC      &lt;--</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">mg</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/plot-mogen-1.png" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The plot traces AIC and BIC as functions of the Markov order. Because higher-order models always fit better in terms of raw log-likelihood (their parameter space contains the lower-order one), the meaningful comparison is between fit and complexity. AIC penalises each parameter by 2; BIC penalises by <code>log(n)</code>, which for this dataset is much larger than 2 — so BIC favors small orders much more aggressively than AIC.</p>
<section class="level3"><h3 id="interpreting-the-results">Interpreting the results<a class="anchor" aria-label="anchor" href="#interpreting-the-results"></a>
</h3>
<ul>
<li>
<strong>Order 0</strong>: Actions are independent — no sequential structure.</li>
<li>
<strong>Order 1</strong>: The standard Markov model is sufficient.</li>
<li>
<strong>Order 2+</strong>: Higher-order dependencies exist. A first-order TNA would miss them.</li>
</ul>
<p>Even when order 1 is globally optimal (by BIC), <em>specific pathways</em> may still exhibit higher-order behavior — the global model averages over all states. The HON analysis below detects these local patterns. The next section adds a complementary, principled hypothesis test that often reveals signal BIC is too parsimonious to flag.</p>
</section><section class="level3"><h3 id="second-order-transition-matrix">Second-order transition matrix<a class="anchor" aria-label="anchor" href="#second-order-transition-matrix"></a>
</h3>
<p><code><a href="../reference/mogen_transitions.html">mogen_transitions()</a></code> extracts the transitions at a given order, showing which two-step contexts lead to different outcomes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mt</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/mogen_transitions.html">mogen_transitions</a></span><span class="op">(</span><span class="va">mg</span>, order <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">mt</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">8</span>, <span class="op">]</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             path count probability               from
1   Specify -&gt; Command -&gt; Specify   281      0.3914 Specify -&gt; Command
2   Command -&gt; Request -&gt; Specify   228      0.7782 Command -&gt; Request
3   Specify -&gt; Command -&gt; Request   198      0.2758 Specify -&gt; Command
4 Request -&gt; Specify -&gt; Interrupt   187      0.3264 Request -&gt; Specify
5   Command -&gt; Command -&gt; Command   163      0.3800 Command -&gt; Command
6 Command -&gt; Specify -&gt; Interrupt   148      0.2792 Command -&gt; Specify
7   Specify -&gt; Request -&gt; Specify   124      0.6526 Specify -&gt; Request
8    Specify -&gt; Refine -&gt; Specify   122      0.6010  Specify -&gt; Refine
         to
1   Specify
2   Specify
3   Request
4 Interrupt
5   Command
6 Interrupt
7   Specify
8   Specify</code></pre>
</div>
</div>
<p>Each row is a second-order pathway. The <code>from</code> column is the two-state context, <code>to</code> is the predicted next state, <code>count</code> is the empirical frequency, and <code>probability</code> is the conditional <code>P(to | from)</code>. A high count combined with a high probability is a <em>predictive</em> context: knowing the previous two states pins down the next one. A high count with low probability is a <em>common but ambiguous</em> context — frequent in the data, but its successor distribution is spread out.</p>
<p><code><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial()</a></code> accepts the <code><a href="../reference/mogen_transitions.html">mogen_transitions()</a></code> data.frame directly. It takes the top pathways by count and renders each as a smooth blob over a shared circular layout, with the path’s intermediate states in blue and the target state in red. Repeated states (like <code>Specify -&gt; Command -&gt; Specify</code>) get distinct positions so the blob covers three visually distinct nodes rather than collapsing to a line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span><span class="op">(</span><span class="va">net</span>, pathways <span class="op">=</span> <span class="va">mt</span>, max_pathways <span class="op">=</span> <span class="fl">6</span>,</span>
<span>                title <span class="op">=</span> <span class="st">"Top 6 second-order pathways"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/mogen-transitions-simplicial-1.png" width="1056"></p>
</figure>
</div>
</div>
</div>
<p>To zoom in on the single most frequent pathway, set <code>max_pathways = 1</code> and let the data.frame drive the selection. Because <code><a href="../reference/mogen_transitions.html">mogen_transitions()</a></code> returns rows already sorted by count, <code>max_pathways = N</code> always picks the top <code>N</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span><span class="op">(</span><span class="va">net</span>, pathways <span class="op">=</span> <span class="va">mt</span>, max_pathways <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/mogen-transitions-single-1.png" width="864"></p>
</figure>
</div>
</div>
</div>
</section><section class="level3"><h3 id="permutation-exact-markov-order-test">Permutation-exact Markov order test<a class="anchor" aria-label="anchor" href="#permutation-exact-markov-order-test"></a>
</h3>
<p>MOGen uses information criteria. A complementary, principled approach is the <strong>permutation-exact LRT</strong> in <code><a href="../reference/markov_order_test.html">markov_order_test()</a></code>: at each order <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>k</mi><annotation encoding="application/x-tex">k</annotation></semantics></math>, it tests <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>H</mi><mn>0</mn></msub><annotation encoding="application/x-tex">H_0</annotation></semantics></math>: “process is order <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo stretchy="true" form="prefix">(</mo><mi>k</mi><mo>−</mo><mn>1</mn><mo stretchy="true" form="postfix">)</mo></mrow><annotation encoding="application/x-tex">(k-1)</annotation></semantics></math>” against <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>H</mi><mn>1</mn></msub><annotation encoding="application/x-tex">H_1</annotation></semantics></math>: “process is order <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>k</mi><annotation encoding="application/x-tex">k</annotation></semantics></math>” by reframing as a conditional-independence test on <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo stretchy="true" form="prefix">(</mo><mi>k</mi><mo>+</mo><mn>1</mn><mo stretchy="true" form="postfix">)</mo></mrow><annotation encoding="application/x-tex">(k+1)</annotation></semantics></math>-grams. The null distribution is built by <strong>shuffling successor labels within each context</strong> — so the test is exact under <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>H</mi><mn>0</mn></msub><annotation encoding="application/x-tex">H_0</annotation></semantics></math>, with no plug-in MLE bias from sparse <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo stretchy="true" form="prefix">(</mo><mi>k</mi><mo>+</mo><mn>1</mn><mo stretchy="true" form="postfix">)</mo></mrow><annotation encoding="application/x-tex">(k+1)</annotation></semantics></math>-gram tables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mot</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/markov_order_test.html">markov_order_test</a></span><span class="op">(</span><span class="va">net</span>, max_order <span class="op">=</span> <span class="fl">3</span>, n_perm <span class="op">=</span> <span class="fl">200</span>, seed <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">mot</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Markov Order Test  [within-w permutation, n_perm = 200, alpha = 0.050]
  508 sequences / 10778 observations / 9 states

  Selected order  BIC: 1   AIC: 3   permutation-LRT: 3

 order    loglik      AIC      BIC   df      g2 p_permutation  p_asymptotic
     0 -22001.20 44018.40 44076.68   NA      NA            NA            NA
     1 -20805.61 41771.23 42354.05   64 2365.38   0.004975124  0.000000e+00
     2 -19819.55 41041.10 46148.07  576 1817.12   0.004975124 1.702866e-128
     3 -17152.10 40596.20 63515.63 4706 5163.79   0.004975124  2.317583e-06
 significant
          NA
        TRUE
        TRUE
        TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">mot</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/markov-order-1.png" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>The output reveals a tension that is hidden by any single criterion. <strong>BIC</strong> selects the smallest order (heavy parsimony penalty). <strong>AIC</strong> and the <strong>permutation LRT</strong> both flag higher orders as significantly better — every increase in order yields a <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msup><mi>G</mi><mn>2</mn></msup><annotation encoding="application/x-tex">G^2</annotation></semantics></math> statistic far in the tail of the within-context permutation null. The right panel makes this concrete: the grey density is the null <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msup><mi>G</mi><mn>2</mn></msup><annotation encoding="application/x-tex">G^2</annotation></semantics></math> distribution per order, and the colored vertical line is the observed value. When the line sits in the right tail, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>H</mi><mn>0</mn></msub><annotation encoding="application/x-tex">H_0</annotation></semantics></math> is rejected and the higher order carries genuine information beyond the previous one.</p>
<p>The takeaway: sequential memory exists in this dataset. BIC penalises it because the parameter space at order 3 is enormous (4,706 degrees of freedom for the order-3 test alone), but the data does pay the cost.</p>
</section><section class="level3"><h3 id="per-state-predictability-transition-entropy">Per-state predictability: transition entropy<a class="anchor" aria-label="anchor" href="#per-state-predictability-transition-entropy"></a>
</h3>
<p>Order-selection answers a global question. <strong>Transition entropy</strong> answers a per-state question: how predictable is each state’s next move? <code><a href="../reference/transition_entropy.html">transition_entropy()</a></code> computes the Shannon row-entropy <code>H(P[i, ]) = -sum_j P[i,j] log P[i,j]</code> for every state, the chain-level entropy rate <code>h(P) = sum_i pi_i H(P[i, ])</code> (the Shannon-McMillan-Breiman per-step uncertainty under the stationary distribution <code>pi</code>), and the redundancy <code>H(pi) - h(P)</code> (how much the previous state reduces uncertainty about the next).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">te</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/transition_entropy.html">transition_entropy</a></span><span class="op">(</span><span class="va">net</span><span class="op">)</span></span>
<span><span class="va">te</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Transition Entropy (9 states, bits; ceiling = 3.170)

                          raw            normalised
  Entropy rate    h(P)  = 2.815 bits    0.888
  Stationary    H(pi)  = 2.983 bits    0.941
  Redundancy   H(pi)-h = 0.167 bits    0.056

Normalised: h(P) and H(pi) are raw / log_2(n_states) (0 = deterministic, 1 = uniform);
  redundancy is the relative redundancy (H(pi) - h(P)) / H(pi), not raw / log_2(n_states).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">te</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/transition-entropy-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Each bar is a state’s outgoing-distribution entropy in bits; the bar’s <strong>width is proportional to the stationary probability</strong>, so the visual area sums to the entropy rate <code>h(P)</code>. The dashed red line marks <code>h(P)</code>; the dotted line marks the ceiling <code>log_2(n)</code> where every state has a uniform outgoing distribution. States whose bar pokes near the ceiling are unpredictable hubs (their next state is essentially random); short bars are deterministic — once you arrive there, the next step is largely fixed.</p>
</section></section><section class="level2"><h2 id="higher-order-networks-hon">Higher-Order Networks (HON)<a class="anchor" aria-label="anchor" href="#higher-order-networks-hon"></a>
</h2>
<p>While MOGen tells us <em>whether</em> higher-order dependencies exist on average, the <strong>Higher-Order Network</strong> (HON; Xu et al. 2016) tells us <em>where</em>. HON tests, for each state, whether adding context significantly changes the outgoing transition distribution using KL-divergence. If the distribution after <em>Request → Specify</em> differs from <em>Frustrate → Specify</em>, HON creates separate nodes for these contexts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">hon</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_hon.html">build_hon</a></span><span class="op">(</span><span class="va">net</span><span class="op">)</span></span>
<span><span class="va">hon</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Higher-Order Network (HON)
  Nodes:        977 (9 first-order states)
  Edges:        3733
  Max order:    5 (requested 5)
  Min freq:     1
  Trajectories: 508</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="../reference/pathways.html">pathways</a></span><span class="op">(</span><span class="va">hon</span>, top <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Specify Command -&gt; Specify"
 [2] "Command Request -&gt; Specify"
 [3] "Specify Command -&gt; Request"
 [4] "Request Specify -&gt; Interrupt"
 [5] "Specify Command Request -&gt; Specify"
 [6] "Command Command -&gt; Command"
 [7] "Command Specify -&gt; Interrupt"
 [8] "Command Request Specify -&gt; Interrupt"
 [9] "Specify Command Specify -&gt; Interrupt"
[10] "Specify Request -&gt; Specify"          </code></pre>
</div>
</div>
<p>Out of 3733 total edges, <strong>3652</strong> (98%) are higher-order — transitions where the preceding context changes the outcome. Look for pathways where the higher-order probability differs substantially from the first-order probability — these represent genuine contextual effects.</p>
<section class="level3"><h3 id="raw-path-frequencies">Raw path frequencies<a class="anchor" aria-label="anchor" href="#raw-path-frequencies"></a>
</h3>
<p>The most common 3-step sequences regardless of statistical significance:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="../reference/path_counts.html">path_counts</a></span><span class="op">(</span><span class="va">net</span>, k <span class="op">=</span> <span class="fl">3</span>, top <span class="op">=</span> <span class="fl">15</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              path count proportion
1    Specify -&gt; Command -&gt; Specify   281     0.0288
2    Command -&gt; Request -&gt; Specify   228     0.0234
3    Specify -&gt; Command -&gt; Request   198     0.0203
4  Request -&gt; Specify -&gt; Interrupt   187     0.0192
5    Command -&gt; Command -&gt; Command   163     0.0167
6  Command -&gt; Specify -&gt; Interrupt   148     0.0152
7    Specify -&gt; Request -&gt; Specify   124     0.0127
8     Specify -&gt; Refine -&gt; Specify   122     0.0125
9    Specify -&gt; Specify -&gt; Specify   121     0.0124
10 Specify -&gt; Interrupt -&gt; Command   109     0.0112
11   Command -&gt; Specify -&gt; Command   106     0.0109
12   Request -&gt; Specify -&gt; Specify    94     0.0096
13   Specify -&gt; Command -&gt; Command    93     0.0095
14   Command -&gt; Specify -&gt; Specify    76     0.0078
15   Specify -&gt; Specify -&gt; Command    76     0.0078</code></pre>
</div>
</div>
</section></section><section class="level2"><h2 id="path-anomaly-detection-hypa">Path Anomaly Detection (HYPA)<a class="anchor" aria-label="anchor" href="#path-anomaly-detection-hypa"></a>
</h2>
<p>HON detects <em>where</em> higher-order structure exists. <strong>HYPA</strong> (LaRock et al. 2020) takes a complementary approach: it detects which specific paths occur <em>significantly more or less often than expected</em> under a null model.</p>
<p>HYPA constructs a De Bruijn graph and computes expected path frequencies using a <strong>multi-hypergeometric null model</strong>: given the in- and out-degrees of every node in the De Bruijn graph, what is the chance distribution over path frequencies if the edges were assigned uniformly at random subject to those degree constraints? Paths whose observed frequency falls in the upper or lower tail of this null are flagged:</p>
<ul>
<li>
<strong>Over-represented</strong> paths occur far more often than the degree-preserving null predicts. They represent <strong>learned behavioural routines</strong> — sequences the actors return to more reliably than their constituent transitions alone would suggest.</li>
<li>
<strong>Under-represented</strong> paths are <em>systematically avoided</em> — observed far less than chance. They reveal sequences that are pragmatically discouraged: cognitively redundant, socially inappropriate, or practically ineffective for the task at hand.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">hypa</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_hypa.html">build_hypa</a></span><span class="op">(</span><span class="va">net</span><span class="op">)</span></span>
<span><span class="va">hypa</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>HYPA: Path Anomaly Detection
  Order(s):     2
  Edges:        702
  Anomalous:    177 (alpha=0.05, p_adjust=BH)
    Over-repr:  133
    Under-repr: 44</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span><span class="op">(</span><span class="va">hypa</span>, dismantled <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/hypa-1.png" width="1440"></p>
</figure>
</div>
</div>
</div>
<section class="level3"><h3 id="over-represented-pathways">Over-represented pathways<a class="anchor" aria-label="anchor" href="#over-represented-pathways"></a>
</h3>
<p>Top over-represented paths sorted by ratio (observed / expected):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">hypa</span>, type <span class="op">=</span> <span class="st">"over"</span>, order_by <span class="op">=</span> <span class="st">"ratio"</span>, n <span class="op">=</span> <span class="fl">8</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>HYPA Summary

  Order(s): 2 | Edges: 702
  Alpha: 0.05 | p_adjust: BH
  Anomalous: 177 (over: 133, under: 44) | order_by: ratio

  Over-represented (top 8 ):
                                path observed  expected     ratio       p_tail
 Interrupt -&gt; Interrupt -&gt; Interrupt       29 2.7844871 10.414844 5.398941e-20
      Verify -&gt; Interrupt -&gt; Request        5 0.6879572  7.267894 7.213367e-04
    Frustrate -&gt; Verify -&gt; Frustrate       27 3.8139380  7.079297 1.082539e-14
      Refine -&gt; Interrupt -&gt; Correct        6 0.8519593  7.042590 2.547426e-04
         Verify -&gt; Verify -&gt; Inquire       10 1.4568505  6.864122 3.120114e-06
         Refine -&gt; Inquire -&gt; Refine        8 1.2069424  6.628320 3.795876e-05
 Interrupt -&gt; Frustrate -&gt; Interrupt       12 2.0454124  5.866788 1.679456e-06
       Verify -&gt; Frustrate -&gt; Verify       22 3.9821999  5.524584 3.057447e-10</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  order                                path observed  expected     ratio
1     2 Interrupt -&gt; Interrupt -&gt; Interrupt       29 2.7844871 10.414844
2     2      Verify -&gt; Interrupt -&gt; Request        5 0.6879572  7.267894
3     2    Frustrate -&gt; Verify -&gt; Frustrate       27 3.8139380  7.079297
4     2      Refine -&gt; Interrupt -&gt; Correct        6 0.8519593  7.042590
5     2         Verify -&gt; Verify -&gt; Inquire       10 1.4568505  6.864122
6     2         Refine -&gt; Inquire -&gt; Refine        8 1.2069424  6.628320
7     2 Interrupt -&gt; Frustrate -&gt; Interrupt       12 2.0454124  5.866788
8     2       Verify -&gt; Frustrate -&gt; Verify       22 3.9821999  5.524584
        p_tail direction
1 5.398941e-20      over
2 7.213367e-04      over
3 1.082539e-14      over
4 2.547426e-04      over
5 3.120114e-06      over
6 3.795876e-05      over
7 1.679456e-06      over
8 3.057447e-10      over</code></pre>
</div>
</div>
<p>In this dataset the top-ratio over-represented paths are typically frustration cascades and inquiry-correction loops — composite routines built from transitions that are individually unremarkable but, when chained, occur many times more often than their degrees alone would suggest.</p>
<p><code>plot_simplicial(hypa, anomaly = "over", dismantled = TRUE)</code> renders one panel per anomalous path so each routine is visible without overlap. Pathways are ranked by ratio, so the most extreme over-representations appear first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span><span class="op">(</span><span class="va">hypa</span>, anomaly <span class="op">=</span> <span class="st">"over"</span>, max_pathways <span class="op">=</span> <span class="fl">9</span>,</span>
<span>                dismantled <span class="op">=</span> <span class="cn">TRUE</span>, ncol <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/hypa-over-1.png" width="1344"></p>
</figure>
</div>
</div>
</div>
</section><section class="level3"><h3 id="under-represented-pathways">Under-represented pathways<a class="anchor" aria-label="anchor" href="#under-represented-pathways"></a>
</h3>
<p>Paths the data actively avoids. The ratios here are typically far from 1.0 in the <em>other</em> direction: observed counts are a fraction of expected, often with very small p-values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">hypa</span>, type <span class="op">=</span> <span class="st">"under"</span>, order_by <span class="op">=</span> <span class="st">"ratio"</span>, n <span class="op">=</span> <span class="fl">8</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>HYPA Summary

  Order(s): 2 | Edges: 702
  Alpha: 0.05 | p_adjust: BH
  Anomalous: 177 (over: 133, under: 44) | order_by: ratio

  Under-represented (top 8 ):
                              path observed  expected     ratio       p_tail
   Inquire -&gt; Specify -&gt; Interrupt        5  27.55236 0.1814726 1.677120e-07
   Frustrate -&gt; Specify -&gt; Command        6  30.26160 0.1982711 9.146340e-08
   Specify -&gt; Specify -&gt; Interrupt       34 148.58597 0.2288238 4.453897e-30
 Frustrate -&gt; Specify -&gt; Interrupt        9  36.40848 0.2471951 5.990496e-08
   Specify -&gt; Command -&gt; Interrupt        8  31.60485 0.2531257 5.922403e-07
   Frustrate -&gt; Command -&gt; Request        5  19.18825 0.2605761 1.313412e-04
    Refine -&gt; Specify -&gt; Interrupt       31 112.17749 0.2763478 7.847657e-20
       Refine -&gt; Specify -&gt; Verify        8  28.65139 0.2792185 5.388930e-06</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  order                              path observed  expected     ratio
1     2   Inquire -&gt; Specify -&gt; Interrupt        5  27.55236 0.1814726
2     2   Frustrate -&gt; Specify -&gt; Command        6  30.26160 0.1982711
3     2   Specify -&gt; Specify -&gt; Interrupt       34 148.58597 0.2288238
4     2 Frustrate -&gt; Specify -&gt; Interrupt        9  36.40848 0.2471951
5     2   Specify -&gt; Command -&gt; Interrupt        8  31.60485 0.2531257
6     2   Frustrate -&gt; Command -&gt; Request        5  19.18825 0.2605761
7     2    Refine -&gt; Specify -&gt; Interrupt       31 112.17749 0.2763478
8     2       Refine -&gt; Specify -&gt; Verify        8  28.65139 0.2792185
        p_tail direction
1 1.677120e-07     under
2 9.146340e-08     under
3 4.453897e-30     under
4 5.990496e-08     under
5 5.922403e-07     under
6 1.313412e-04     under
7 7.847657e-20     under
8 5.388930e-06     under</code></pre>
</div>
</div>
<p>Notice paths like <code>Specify -&gt; Specify -&gt; Specify -&gt; Specify</code> — a four-step run of pure specification — appear at a small fraction of expected frequency. The transition <code>Specify -&gt; Specify</code> exists in the data, but stacking it four deep is something programmers actively don’t do. The under-represented set captures these <em>negative</em> sequential constraints.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span><span class="op">(</span><span class="va">hypa</span>, anomaly <span class="op">=</span> <span class="st">"under"</span>, max_pathways <span class="op">=</span> <span class="fl">6</span>,</span>
<span>                dismantled <span class="op">=</span> <span class="cn">TRUE</span>, ncol <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/hypa-under-1.png" width="1344"></p>
</figure>
</div>
</div>
</div>
</section><section class="level3"><h3 id="combined-overlay">Combined overlay<a class="anchor" aria-label="anchor" href="#combined-overlay"></a>
</h3>
<p>Multiple pathways on a single plot — overlapping regions indicate states that participate in many higher-order patterns:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span><span class="op">(</span><span class="va">net</span>, max_pathways <span class="op">=</span> <span class="fl">6</span>,</span>
<span>                title <span class="op">=</span> <span class="st">"Top 6 Higher-Order Pathways"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/simplicial-combined-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section></section><section class="level2"><h2 id="higher-order-analysis-across-groups">Higher-Order Analysis Across Groups<a class="anchor" aria-label="anchor" href="#higher-order-analysis-across-groups"></a>
</h2>
<p>A powerful application is comparing higher-order structure across conditions. We build grouped networks by cluster (Directive, Evaluative, Metacognitive) and run HYPA on each:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">grp_net</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_network.html">build_network</a></span><span class="op">(</span><span class="va">human_long</span>, method <span class="op">=</span> <span class="st">"relative"</span>,</span>
<span>                         action <span class="op">=</span> <span class="st">"code"</span>, actor <span class="op">=</span> <span class="st">"session_id"</span>,</span>
<span>                         time <span class="op">=</span> <span class="st">"timestamp"</span>, group <span class="op">=</span> <span class="st">"cluster"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hypa_results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html" class="external-link">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html" class="external-link">names</a></span><span class="op">(</span><span class="va">grp_net</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">nm</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">h</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_hypa.html">build_hypa</a></span><span class="op">(</span><span class="va">grp_net</span><span class="op">[[</span><span class="va">nm</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html" class="external-link">data.frame</a></span><span class="op">(</span></span>
<span>    group <span class="op">=</span> <span class="va">nm</span>,</span>
<span>    total_edges <span class="op">=</span> <span class="va">h</span><span class="op">$</span><span class="va">n_edges</span>,</span>
<span>    anomalous <span class="op">=</span> <span class="va">h</span><span class="op">$</span><span class="va">n_anomalous</span>,</span>
<span>    over <span class="op">=</span> <span class="va">h</span><span class="op">$</span><span class="va">n_over</span>,</span>
<span>    under <span class="op">=</span> <span class="va">h</span><span class="op">$</span><span class="va">n_under</span>,</span>
<span>    pct_anomalous <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="fl">100</span> <span class="op">*</span> <span class="va">h</span><span class="op">$</span><span class="va">n_anomalous</span> <span class="op">/</span> <span class="va">h</span><span class="op">$</span><span class="va">n_edges</span>, <span class="fl">1</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/do.call.html" class="external-link">do.call</a></span><span class="op">(</span><span class="va">rbind</span>, <span class="va">hypa_results</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          group total_edges anomalous over under pct_anomalous
1     Directive          27        22   11    11          81.5
2 Metacognitive           8         7    4     3          87.5
3    Evaluative          64        13    9     4          20.3</code></pre>
</div>
</div>
<p>Groups with a higher percentage of anomalous pathways have more higher-order structure — their sequential dynamics are less predictable from first-order transitions alone.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html" class="external-link">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span><span class="op">(</span><span class="va">grp_net</span><span class="op">$</span><span class="va">Directive</span>, max_pathways <span class="op">=</span> <span class="fl">4</span>,</span>
<span>                title <span class="op">=</span> <span class="st">"Directive: Higher-Order Pathways"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/group-simplicial-1.png" width="1344"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span><span class="op">(</span><span class="va">grp_net</span><span class="op">$</span><span class="va">Evaluative</span>, max_pathways <span class="op">=</span> <span class="fl">4</span>,</span>
<span>                title <span class="op">=</span> <span class="st">"Evaluative: Higher-Order Pathways"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/group-simplicial-2.png" width="1344"></p>
</figure>
</div>
</div>
</div>
</section><section class="level2"><h2 id="comparing-datasets">Comparing Datasets<a class="anchor" aria-label="anchor" href="#comparing-datasets"></a>
</h2>
<p>Higher-order analysis is particularly informative when applied to different datasets. Here we compare the human-AI coding data with a collaborative regulation dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="st">"group_regulation_long"</span>, package <span class="op">=</span> <span class="st">"Nestimate"</span><span class="op">)</span></span>
<span><span class="va">net_reg</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_network.html">build_network</a></span><span class="op">(</span><span class="va">group_regulation_long</span>, method <span class="op">=</span> <span class="st">"relative"</span>,</span>
<span>                         action <span class="op">=</span> <span class="st">"Action"</span>, actor <span class="op">=</span> <span class="st">"Actor"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hypa_coding</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_hypa.html">build_hypa</a></span><span class="op">(</span><span class="va">net</span><span class="op">)</span></span>
<span><span class="va">hypa_reg</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_hypa.html">build_hypa</a></span><span class="op">(</span><span class="va">net_reg</span><span class="op">)</span></span>
<span></span>
<span><span class="va">comparison</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html" class="external-link">data.frame</a></span><span class="op">(</span></span>
<span>  dataset <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"Human-AI Coding"</span>, <span class="st">"Collaborative Regulation"</span><span class="op">)</span>,</span>
<span>  nodes <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">net</span><span class="op">$</span><span class="va">n_nodes</span>, <span class="va">net_reg</span><span class="op">$</span><span class="va">n_nodes</span><span class="op">)</span>,</span>
<span>  total_paths <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">hypa_coding</span><span class="op">$</span><span class="va">n_edges</span>, <span class="va">hypa_reg</span><span class="op">$</span><span class="va">n_edges</span><span class="op">)</span>,</span>
<span>  anomalous <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">hypa_coding</span><span class="op">$</span><span class="va">n_anomalous</span>, <span class="va">hypa_reg</span><span class="op">$</span><span class="va">n_anomalous</span><span class="op">)</span>,</span>
<span>  over <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">hypa_coding</span><span class="op">$</span><span class="va">n_over</span>, <span class="va">hypa_reg</span><span class="op">$</span><span class="va">n_over</span><span class="op">)</span>,</span>
<span>  under <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">hypa_coding</span><span class="op">$</span><span class="va">n_under</span>, <span class="va">hypa_reg</span><span class="op">$</span><span class="va">n_under</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="va">comparison</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   dataset nodes total_paths anomalous over under
1          Human-AI Coding     9         702       177  133    44
2 Collaborative Regulation     9         574       229  174    55</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html" class="external-link">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span><span class="op">(</span><span class="va">net</span>, max_pathways <span class="op">=</span> <span class="fl">4</span>,</span>
<span>                title <span class="op">=</span> <span class="st">"Human-AI Coding"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/compare-simplicial-1.png" width="1344"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial</a></span><span class="op">(</span><span class="va">net_reg</span>, max_pathways <span class="op">=</span> <span class="fl">4</span>,</span>
<span>                title <span class="op">=</span> <span class="st">"Collaborative Regulation"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/compare-simplicial-2.png" width="1344"></p>
</figure>
</div>
</div>
</div>
<p>Different domains produce different higher-order signatures. Comparing these reveals whether sequential memory is a universal property of the behavioral system or specific to particular tasks.</p>
</section><section class="level2"><h2 id="simplicial-complex-analysis">Simplicial Complex Analysis<a class="anchor" aria-label="anchor" href="#simplicial-complex-analysis"></a>
</h2>
<p>All the methods above analyze sequential pathways. <strong>Simplicial complex analysis</strong> takes a different perspective: it examines the <strong>topological structure</strong> of the network itself.</p>
<section class="level3"><h3 id="what-is-a-simplicial-complex">What is a simplicial complex?<a class="anchor" aria-label="anchor" href="#what-is-a-simplicial-complex"></a>
</h3>
<p>A standard network captures pairwise relationships: node A connects to node B. But many interactions involve <strong>groups</strong>: states A, B, and C may all be densely interconnected, forming a triangle. A simplicial complex formalizes this:</p>
<ul>
<li>A <strong>0-simplex</strong> is a single node</li>
<li>A <strong>1-simplex</strong> is an edge (two connected nodes)</li>
<li>A <strong>2-simplex</strong> is a filled triangle (three mutually connected nodes)</li>
<li>A <strong><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>k</mi><annotation encoding="application/x-tex">k</annotation></semantics></math>-simplex</strong> is a group of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>k</mi><mo>+</mo><mn>1</mn></mrow><annotation encoding="application/x-tex">k+1</annotation></semantics></math> mutually connected nodes</li>
</ul>
<p>The <strong>clique complex</strong> turns every clique into a simplex, lifting a flat graph into a multi-dimensional topological object.</p>
</section><section class="level3"><h3 id="building-the-complex">Building the complex<a class="anchor" aria-label="anchor" href="#building-the-complex"></a>
</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">sc</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_simplicial.html">build_simplicial</a></span><span class="op">(</span><span class="va">net</span>, threshold <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span></span>
<span><span class="va">sc</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Clique Complex
  9 nodes, 511 simplices, dimension 8
  Density: 100.0%  |  Mean dim: 3.51  |  Euler: 1
  f-vector: (f0=9 f1=36 f2=84 f3=126 f4=126 f5=84 f6=36 f7=9 f8=1)
  Betti: b0=1
  Nodes: Command, Correct, Frustrate, Inquire, Interrupt, Refine, Request, Specify, Verify </code></pre>
</div>
</div>
</section><section class="level3"><h3 id="topological-descriptors">Topological descriptors<a class="anchor" aria-label="anchor" href="#topological-descriptors"></a>
</h3>
<ul>
<li>
<strong>f-vector</strong> <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo stretchy="true" form="prefix">(</mo><msub><mi>f</mi><mn>0</mn></msub><mo>,</mo><msub><mi>f</mi><mn>1</mn></msub><mo>,</mo><msub><mi>f</mi><mn>2</mn></msub><mo>,</mo><mi>…</mi><mo stretchy="true" form="postfix">)</mo></mrow><annotation encoding="application/x-tex">(f_0, f_1, f_2, \ldots)</annotation></semantics></math>: counts simplices at each dimension.</li>
<li>
<strong>Betti numbers</strong> <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo stretchy="true" form="prefix">(</mo><msub><mi>β</mi><mn>0</mn></msub><mo>,</mo><msub><mi>β</mi><mn>1</mn></msub><mo>,</mo><msub><mi>β</mi><mn>2</mn></msub><mo>,</mo><mi>…</mi><mo stretchy="true" form="postfix">)</mo></mrow><annotation encoding="application/x-tex">(\beta_0, \beta_1, \beta_2, \ldots)</annotation></semantics></math>: the central invariants. <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>0</mn></msub><annotation encoding="application/x-tex">\beta_0</annotation></semantics></math> = connected components, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>1</mn></msub><annotation encoding="application/x-tex">\beta_1</annotation></semantics></math> = independent loops, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>2</mn></msub><annotation encoding="application/x-tex">\beta_2</annotation></semantics></math> = enclosed voids.</li>
<li>
<strong>Euler characteristic</strong> <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>χ</mi><mo>=</mo><mo>∑</mo><msup><mrow><mo stretchy="true" form="prefix">(</mo><mi>−</mi><mn>1</mn><mo stretchy="true" form="postfix">)</mo></mrow><mi>k</mi></msup><msub><mi>f</mi><mi>k</mi></msub><mo>=</mo><mo>∑</mo><msup><mrow><mo stretchy="true" form="prefix">(</mo><mi>−</mi><mn>1</mn><mo stretchy="true" form="postfix">)</mo></mrow><mi>k</mi></msup><msub><mi>β</mi><mi>k</mi></msub></mrow><annotation encoding="application/x-tex">\chi = \sum (-1)^k f_k = \sum (-1)^k \beta_k</annotation></semantics></math>. For a contractible complex, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>χ</mi><mo>=</mo><mn>1</mn></mrow><annotation encoding="application/x-tex">\chi = 1</annotation></semantics></math>.</li>
<li>
<strong>Simplicial degree</strong>: how many higher-dimensional simplices each node participates in.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="../reference/simplicial_degree.html">simplicial_degree</a></span><span class="op">(</span><span class="va">sc</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       node d0 d1 d2 d3 d4 d5 d6 d7 d8 total
1   Command  1  8 28 56 70 56 28  8  1   255
2   Correct  1  8 28 56 70 56 28  8  1   255
3 Frustrate  1  8 28 56 70 56 28  8  1   255
4   Inquire  1  8 28 56 70 56 28  8  1   255
5 Interrupt  1  8 28 56 70 56 28  8  1   255
6    Refine  1  8 28 56 70 56 28  8  1   255
7   Request  1  8 28 56 70 56 28  8  1   255
8   Specify  1  8 28 56 70 56 28  8  1   255
9    Verify  1  8 28 56 70 56 28  8  1   255</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">sc</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/plot-sc-1.png" width="1248"></p>
</figure>
</div>
</div>
</div>
<p>The four panels show:</p>
<ul>
<li>
<strong>f-vector</strong> (top-left): the number of simplices at each dimension. A long descending sequence with non-trivial counts at <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>k</mi><mo>≥</mo><mn>2</mn></mrow><annotation encoding="application/x-tex">k \geq 2</annotation></semantics></math> means the network has many small densely-connected pockets, not just edges.</li>
<li>
<strong>Betti numbers</strong> (top-right): the central topological invariants, with the Euler characteristic in the subtitle. <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>0</mn></msub><annotation encoding="application/x-tex">\beta_0</annotation></semantics></math> counts disconnected components; <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>1</mn></msub><annotation encoding="application/x-tex">\beta_1</annotation></semantics></math> is the number of independent loops (1-cycles that aren’t filled); <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>2</mn></msub><annotation encoding="application/x-tex">\beta_2</annotation></semantics></math> counts enclosed 3D voids.</li>
<li>
<strong>Simplicial degree</strong> (bottom-left): per-node participation in simplices of dimension <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo>≥</mo><mn>1</mn></mrow><annotation encoding="application/x-tex">\geq 1</annotation></semantics></math>. The most simplicially-active nodes are the topological hubs. This number can disagree with the pairwise-degree ranking — a node can have many edges but participate in few cliques.</li>
<li>
<strong>Degree by dimension</strong> (bottom-right): the same participation, broken out by simplex dimension. A node that contributes mostly to high-dimensional simplices is part of densely-clustered subgroups; one whose row is concentrated at <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>k</mi><mo>=</mo><mn>1</mn></mrow><annotation encoding="application/x-tex">k = 1</annotation></semantics></math> has many edges but few clique-memberships.</li>
</ul></section><section class="level3"><h3 id="persistent-homology">Persistent Homology<a class="anchor" aria-label="anchor" href="#persistent-homology"></a>
</h3>
<p>A single complex at one threshold gives a static snapshot. <strong>Persistent homology</strong> reveals how topology evolves as we vary the threshold. Start with only the strongest edges and progressively add weaker ones. Features that persist across a wide range are <strong>topologically robust</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ph</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/persistent_homology.html">persistent_homology</a></span><span class="op">(</span><span class="va">net</span>, n_steps <span class="op">=</span> <span class="fl">25</span><span class="op">)</span></span>
<span><span class="va">ph</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Persistent Homology
  25 filtration steps [0.6197 → 0.0062]
  Features: b0: 8 (1 persistent)  |  b1: 3 (0 persistent)  |  b3: 70 (70 persistent)
  Longest-lived:
    b0: 0.6197 → 0.0000 (life: 0.6197)
    b0: 0.6197 → 0.1707 (life: 0.4491)
    b0: 0.6197 → 0.1958 (life: 0.4239)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">ph</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/persistent-1.png" width="1248"></p>
</figure>
</div>
</div>
</div>
<p><strong>Betti curve</strong> (left) — read it as a <em>filtration in reverse</em>: start with only the strongest edges (high threshold = a sparse graph, many components, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>0</mn></msub><annotation encoding="application/x-tex">\beta_0</annotation></semantics></math> large) and trace what happens as the threshold drops and weaker edges are added. Components merge into one another so <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>0</mn></msub><annotation encoding="application/x-tex">\beta_0</annotation></semantics></math> falls; new loops appear (so <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>1</mn></msub><annotation encoding="application/x-tex">\beta_1</annotation></semantics></math> jumps up) and later get filled in by triangles (so <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>1</mn></msub><annotation encoding="application/x-tex">\beta_1</annotation></semantics></math> falls again). The shape of these curves is a fingerprint of the network’s topology — a smooth monotone <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>0</mn></msub><annotation encoding="application/x-tex">\beta_0</annotation></semantics></math> curve means the graph is well-connected at every scale, while a long flat plateau with sudden drops marks discrete merging events.</p>
<p><strong>Persistence diagram</strong> (right): each point is one topological feature, plotted at its (birth threshold, death threshold). Points hug the diagonal when birth and death are close — those are short-lived features, almost certainly noise. Points far above the diagonal lived through a wide range of thresholds and are the <em>robust</em> topological signal. Color encodes dimension; size encodes persistence (death − birth) so the most persistent features pop visually.</p>
</section><section class="level3"><h3 id="q-analysis">Q-Analysis<a class="anchor" aria-label="anchor" href="#q-analysis"></a>
</h3>
<p>Q-analysis (Atkin 1974) measures connectivity at multiple levels of structural sharing. Two maximal simplices are <strong>q-connected</strong> if they share a face of dimension <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo>≥</mo><mi>q</mi></mrow><annotation encoding="application/x-tex">\geq q</annotation></semantics></math>:</p>
<ul>
<li>
<strong>q = 0</strong>: share at least one node</li>
<li>
<strong>q = 1</strong>: share at least one edge</li>
<li>
<strong>q = 2</strong>: share at least one triangle</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">qa</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/q_analysis.html">q_analysis</a></span><span class="op">(</span><span class="va">sc</span><span class="op">)</span></span>
<span><span class="va">qa</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Q-Analysis (max q = 8)
  Components: q8:1 q7:1 q6:1 q5:1 q4:1 q3:1 q2:1 q1:1 q0:1
  Fully connected at all q levels
  Structure: Command:8 Correct:8 Frustrate:8 Inquire:8 Interrupt:8 Refine:8 Request:8 Specify:8 Verify:8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">qa</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/q-analysis-1.png" width="1248"></p>
</figure>
</div>
</div>
</div>
<p>The left panel is the <strong>Q-vector</strong>: number of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>q</mi><annotation encoding="application/x-tex">q</annotation></semantics></math>-connected components at each level <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>q</mi><annotation encoding="application/x-tex">q</annotation></semantics></math>, plotted right-to-left as <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>q</mi><annotation encoding="application/x-tex">q</annotation></semantics></math> decreases. Read it as a fragmentation profile of the complex.</p>
<ul>
<li>At very high <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>q</mi><annotation encoding="application/x-tex">q</annotation></semantics></math>: only simplices that share a large face are linked. Most simplices stand alone, so the component count is high.</li>
<li>As <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>q</mi><annotation encoding="application/x-tex">q</annotation></semantics></math> drops: the connectivity criterion relaxes. Simplices that share even one or two vertices now count as connected, so components merge and the count falls.</li>
<li>At <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>q</mi><mo>=</mo><mn>0</mn></mrow><annotation encoding="application/x-tex">q = 0</annotation></semantics></math>: any two simplices sharing a single vertex are linked. Usually one big component.</li>
</ul>
<p>The <strong>fragmentation point</strong> is the largest <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>q</mi><annotation encoding="application/x-tex">q</annotation></semantics></math> at which the count first rises above 1. Below it the complex hangs together as one piece through high-order shared structure (groups of simplices that overlap in big faces). Above it that high-order glue is broken — sub-structures become isolated islands held together only by sparse low-order overlaps. A high fragmentation point means strong cohesion: many simplices share substantial substructure. A low one means simplices are stitched together mostly through one or two shared vertices, with no deep shared structure.</p>
<p>The right panel shows the <strong>structure vector</strong>: the maximum simplex dimension each node participates in, sorted descending. Nodes at the top are members of the densest clique-groups in the network.</p>
</section><section class="level3"><h3 id="pathway-complex-from-hon">Pathway Complex from HON<a class="anchor" aria-label="anchor" href="#pathway-complex-from-hon"></a>
</h3>
<p>An alternative to the clique complex: build a simplicial complex from the <strong>pathways</strong> discovered by HON — topology derived from sequential dynamics rather than network structure:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">sc_hon</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/build_simplicial.html">build_simplicial</a></span><span class="op">(</span><span class="va">hon</span>, type <span class="op">=</span> <span class="st">"pathway"</span>, max_pathways <span class="op">=</span> <span class="fl">30</span><span class="op">)</span></span>
<span><span class="va">sc_hon</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pathway Complex
  9 nodes, 31 simplices, dimension 3
  Density: 12.2%  |  Mean dim: 1.00  |  Euler: 1
  f-vector: (f0=9 f1=14 f2=7 f3=1)
  Betti: b0=2 b1=1
  Nodes: Command, Correct, Frustrate, Inquire, Interrupt, Refine, Request, Specify, Verify </code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">sc_hon</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cograph-tutorial-simplicial_files/figure-html/pathway-complex-1.png" width="1248"></p>
</figure>
</div>
</div>
</div>
<p>In the pathway complex, each higher-order pathway becomes a simplex. <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>β</mi><mn>0</mn></msub><mo>&gt;</mo><mn>1</mn></mrow><annotation encoding="application/x-tex">\beta_0 &gt; 1</annotation></semantics></math> means some states are sequentially disconnected. <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>β</mi><mn>1</mn></msub><mo>&gt;</mo><mn>0</mn></mrow><annotation encoding="application/x-tex">\beta_1 &gt; 0</annotation></semantics></math> means there are cyclic pathway structures.</p>
</section><section class="level3"><h3 id="verification">Verification<a class="anchor" aria-label="anchor" href="#verification"></a>
</h3>
<p>All simplicial computations are cross-validated against igraph’s clique-finding and verified via the Euler-Poincaré theorem:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="../reference/verify_simplicial.html">verify_simplicial</a></span><span class="op">(</span><span class="va">net</span><span class="op">$</span><span class="va">weights</span>, threshold <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Cliques:  MATCH (511 simplices)
  Betti:    b0=1 b1=0 b2=0 b3=0 b4=0 b5=0 b6=0 b7=0 b8=0
  Euler:    1 (Euler-Poincare: VERIFIED)</code></pre>
</div>
</div>
</section></section><section class="level2"><h2 id="summary">Summary<a class="anchor" aria-label="anchor" href="#summary"></a>
</h2>
<table class="table caption-top">
<colgroup>
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 24%">
<col style="width: 41%">
</colgroup>
<thead><tr class="header">
<th>Step</th>
<th>Method</th>
<th>Function</th>
<th>What it reveals</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><strong>TNA</strong></td>
<td><code><a href="../reference/build_network.html">build_network()</a></code></td>
<td>First-order transition structure</td>
</tr>
<tr class="even">
<td>2</td>
<td><strong>MOGen</strong></td>
<td><code><a href="../reference/build_mogen.html">build_mogen()</a></code></td>
<td>Whether higher-order is needed (information criteria)</td>
</tr>
<tr class="odd">
<td>3</td>
<td><strong>Markov order test</strong></td>
<td><code><a href="../reference/markov_order_test.html">markov_order_test()</a></code></td>
<td>Whether higher-order is needed (permutation-exact LRT)</td>
</tr>
<tr class="even">
<td>4</td>
<td><strong>Transition entropy</strong></td>
<td><code><a href="../reference/transition_entropy.html">transition_entropy()</a></code></td>
<td>Per-state predictability and chain entropy rate</td>
</tr>
<tr class="odd">
<td>5</td>
<td><strong>HON</strong></td>
<td><code><a href="../reference/build_hon.html">build_hon()</a></code></td>
<td>Where sequential context changes transitions</td>
</tr>
<tr class="even">
<td>6</td>
<td><strong>HYPA</strong></td>
<td><code><a href="../reference/build_hypa.html">build_hypa()</a></code></td>
<td>Which paths are anomalously frequent or rare</td>
</tr>
<tr class="odd">
<td>7</td>
<td><strong>Visualization</strong></td>
<td><code><a href="https://sonsoles.me/cograph/reference/plot_simplicial.html" class="external-link">plot_simplicial()</a></code></td>
<td>Blob diagrams of pathways (also accepts <code><a href="../reference/mogen_transitions.html">mogen_transitions()</a></code> data.frames)</td>
</tr>
<tr class="even">
<td>8</td>
<td><strong>Simplicial</strong></td>
<td><code><a href="../reference/build_simplicial.html">build_simplicial()</a></code></td>
<td>Topological structure</td>
</tr>
<tr class="odd">
<td>9</td>
<td><strong>Persistence</strong></td>
<td><code><a href="../reference/persistent_homology.html">persistent_homology()</a></code></td>
<td>Robustness across scales</td>
</tr>
<tr class="even">
<td>10</td>
<td><strong>Q-analysis</strong></td>
<td><code><a href="../reference/q_analysis.html">q_analysis()</a></code></td>
<td>Multi-level connectivity</td>
</tr>
</tbody>
</table>
<p>The key progression:</p>
<ul>
<li>
<strong>TNA</strong> answers: <em>what transitions exist?</em>
</li>
<li>
<strong>MOGen + Markov order test</strong> answer: <em>is first-order enough?</em> (and disagree informatively when BIC is conservative)</li>
<li>
<strong>Transition entropy</strong> answers: <em>which states are unpredictable hubs vs. deterministic gateways?</em>
</li>
<li>
<strong>HON</strong> answers: <em>where does context matter?</em>
</li>
<li>
<strong>HYPA</strong> answers: <em>which sequences are surprisingly frequent — or surprisingly avoided?</em>
</li>
<li>
<strong>Simplicial analysis</strong> answers: <em>what is the shape of the interaction space?</em>
</li>
</ul></section><section class="level2"><h2 id="references">References<a class="anchor" aria-label="anchor" href="#references"></a>
</h2>
<ul>
<li>Atkin, R. H. (1974). <em>Mathematical Structure in Human Affairs</em>. Heinemann Educational.</li>
<li>Battiston, F., et al. (2020). Networks beyond pairwise interactions: Structure and dynamics. <em>Physics Reports</em>, 874, 1–92.</li>
<li>LaRock, T., Scholtes, I., &amp; Eliassi-Rad, T. (2020). HYPA: Efficient detection of path anomalies in time series data on networks. <em>EPJ Data Science</em>, 9(1), 15.</li>
<li>Scholtes, I. (2017). When is a network a network? Multi-order graphical model selection in pathways and temporal networks. <em>Proceedings of the 23rd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining</em>, 1037–1046.</li>
<li>Xu, J., Wickramarathne, T. L., &amp; Chawla, N. V. (2016). Representing higher-order dependencies in networks. <em>Science Advances</em>, 2(5), e1600028.</li>
</ul></section><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config);
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by <a href="https://saqr.me" class="external-link">Mohammed Saqr</a>, <a href="https://sonsoles.me" class="external-link">Sonsoles López-Pernas</a>, Kamila Misiejuk.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.0.</p>
</div>

    </footer>
</div>





  </body>
</html>
